name: Latest Medium blog posts

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest Medium posts
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Fetch the Medium blog posts using the blog-post-workflow action
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@ibtesum38"

      # Step 3: Debug: List files to check if latest_blog_posts.md is created
      - name: Debug: List files
        run: |
          ls -alh

      # Step 4: Debug: Display the contents of the fetched blog posts
      - name: Debug: List fetched posts
        run: |
          echo "Listing fetched posts:"
          cat ./latest_blog_posts.md

      # Step 5: Add images to blog posts and update README
      - name: Add images to blog posts and update README
        run: |
          # Read the fetched posts from the file
          posts_file="./latest_blog_posts.md"
          
          # Initialize the styled content for README
          styled_posts="## 📝 Latest Medium Posts\n\n"

          # Loop through each line to format blog posts with images
          while IFS= read -r line; do
            if [[ $line == *"Post Title"* ]]; then
              # Extract the title and link of the post
              post_title=$(echo $line | sed 's/^.*Post Title: //')
              post_link=$(echo $line | sed 's/^.*Link: //')
              # Default image if none is found
              image_url="https://via.placeholder.com/150"

              # Check if image URL is present in the post description
              if [[ $line == *"<media:content"* ]]; then
                image_url=$(echo $line | sed 's/^.*<media:content url="\([^"]*\)".*/\1/')
              fi

              # Add title, link, and image to the styled posts
              styled_posts+=$'\n'"### [${post_title}](${post_link})\n![Image](${image_url})\n"
            fi
          done < "$posts_file"

          # Debug: Print the styled posts content to check the formatting
          echo "Styled posts:"
          echo "$styled_posts"

          # Replace content in README.md between markers
          readme_file="README.md"
          section_start="<!-- BLOG-POST-LIST:START -->"
          section_end="<!-- BLOG-POST-LIST:END -->"

          # Replace content in README
          sed -i "/$section_start/,/$section_end/c\\
          $section_start\\n$styled_posts\\n$section_end" $readme_file

      # Step 6: Commit and push the updated README file
      - name: Commit and push updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Medium blog posts with images"
          git push
